### ISSUE TITLE
Data extraction tool for testing

### ISSUE THREAD

**Issue by JerryVeldhuis** [JerryVeldhuis/IMDB-Local#8]
It might be handy to have a tool that can be given a list of movie and tv series titles and extract out the imdb data and build a set of imdb.list formatted files. 

This could be used for testing new enhancements and compare the side-effects of code changes instead of having to work with the full-sized list files.

**Comment by honir** [comment]
Agree, this would be very helpful (I've done this manually in the past and it takes ages!)

**Comment by JerryVeldhuis** [comment]
added imdb-export2listfiles.pl which currently takes a file with a list of titles to extract.
If a '%' exists in a line then the 'like' operator is used.

If the matching title is of type TV_SERIES the extraction will include all episodes as well.
